# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from at_runner._generated.at.runner.v1 import runner_pb2 as at_dot_runner_dot_v1_dot_runner__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in at/runner/v1/runner_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RunnerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RunSync = channel.unary_unary(
                '/at.runner.v1.Runner/RunSync',
                request_serializer=at_dot_runner_dot_v1_dot_runner__pb2.RunSyncRequest.SerializeToString,
                response_deserializer=at_dot_runner_dot_v1_dot_runner__pb2.RunSyncResponse.FromString,
                _registered_method=True)
        self.UploadFile = channel.stream_unary(
                '/at.runner.v1.Runner/UploadFile',
                request_serializer=at_dot_runner_dot_v1_dot_runner__pb2.FileChunk.SerializeToString,
                response_deserializer=at_dot_runner_dot_v1_dot_runner__pb2.UploadResponse.FromString,
                _registered_method=True)
        self.GetFile = channel.unary_stream(
                '/at.runner.v1.Runner/GetFile',
                request_serializer=at_dot_runner_dot_v1_dot_runner__pb2.GetFileRequest.SerializeToString,
                response_deserializer=at_dot_runner_dot_v1_dot_runner__pb2.FileChunk.FromString,
                _registered_method=True)
        self.DeleteFile = channel.unary_unary(
                '/at.runner.v1.Runner/DeleteFile',
                request_serializer=at_dot_runner_dot_v1_dot_runner__pb2.DeleteFileRequest.SerializeToString,
                response_deserializer=at_dot_runner_dot_v1_dot_runner__pb2.DeleteFileResponse.FromString,
                _registered_method=True)
        self.ListFiles = channel.unary_unary(
                '/at.runner.v1.Runner/ListFiles',
                request_serializer=at_dot_runner_dot_v1_dot_runner__pb2.ListFilesRequest.SerializeToString,
                response_deserializer=at_dot_runner_dot_v1_dot_runner__pb2.ListFilesResponse.FromString,
                _registered_method=True)
        self.Run = channel.unary_stream(
                '/at.runner.v1.Runner/Run',
                request_serializer=at_dot_runner_dot_v1_dot_runner__pb2.RunRequest.SerializeToString,
                response_deserializer=at_dot_runner_dot_v1_dot_runner__pb2.RunOutput.FromString,
                _registered_method=True)
        self.RunPipeline = channel.unary_stream(
                '/at.runner.v1.Runner/RunPipeline',
                request_serializer=at_dot_runner_dot_v1_dot_runner__pb2.RunPipelineRequest.SerializeToString,
                response_deserializer=at_dot_runner_dot_v1_dot_runner__pb2.PipelineOutput.FromString,
                _registered_method=True)


class RunnerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RunSync(self, request, context):
        """--- Tier 1: Simple (unary, self-contained) ---
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UploadFile(self, request_iterator, context):
        """--- Tier 2: Interactive (streaming, session workspace) ---
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListFiles(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Run(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RunPipeline(self, request, context):
        """--- Tier 3: Orchestration (DAG of runs, parallel execution) ---
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RunnerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RunSync': grpc.unary_unary_rpc_method_handler(
                    servicer.RunSync,
                    request_deserializer=at_dot_runner_dot_v1_dot_runner__pb2.RunSyncRequest.FromString,
                    response_serializer=at_dot_runner_dot_v1_dot_runner__pb2.RunSyncResponse.SerializeToString,
            ),
            'UploadFile': grpc.stream_unary_rpc_method_handler(
                    servicer.UploadFile,
                    request_deserializer=at_dot_runner_dot_v1_dot_runner__pb2.FileChunk.FromString,
                    response_serializer=at_dot_runner_dot_v1_dot_runner__pb2.UploadResponse.SerializeToString,
            ),
            'GetFile': grpc.unary_stream_rpc_method_handler(
                    servicer.GetFile,
                    request_deserializer=at_dot_runner_dot_v1_dot_runner__pb2.GetFileRequest.FromString,
                    response_serializer=at_dot_runner_dot_v1_dot_runner__pb2.FileChunk.SerializeToString,
            ),
            'DeleteFile': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteFile,
                    request_deserializer=at_dot_runner_dot_v1_dot_runner__pb2.DeleteFileRequest.FromString,
                    response_serializer=at_dot_runner_dot_v1_dot_runner__pb2.DeleteFileResponse.SerializeToString,
            ),
            'ListFiles': grpc.unary_unary_rpc_method_handler(
                    servicer.ListFiles,
                    request_deserializer=at_dot_runner_dot_v1_dot_runner__pb2.ListFilesRequest.FromString,
                    response_serializer=at_dot_runner_dot_v1_dot_runner__pb2.ListFilesResponse.SerializeToString,
            ),
            'Run': grpc.unary_stream_rpc_method_handler(
                    servicer.Run,
                    request_deserializer=at_dot_runner_dot_v1_dot_runner__pb2.RunRequest.FromString,
                    response_serializer=at_dot_runner_dot_v1_dot_runner__pb2.RunOutput.SerializeToString,
            ),
            'RunPipeline': grpc.unary_stream_rpc_method_handler(
                    servicer.RunPipeline,
                    request_deserializer=at_dot_runner_dot_v1_dot_runner__pb2.RunPipelineRequest.FromString,
                    response_serializer=at_dot_runner_dot_v1_dot_runner__pb2.PipelineOutput.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'at.runner.v1.Runner', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('at.runner.v1.Runner', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Runner(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RunSync(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/at.runner.v1.Runner/RunSync',
            at_dot_runner_dot_v1_dot_runner__pb2.RunSyncRequest.SerializeToString,
            at_dot_runner_dot_v1_dot_runner__pb2.RunSyncResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UploadFile(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/at.runner.v1.Runner/UploadFile',
            at_dot_runner_dot_v1_dot_runner__pb2.FileChunk.SerializeToString,
            at_dot_runner_dot_v1_dot_runner__pb2.UploadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/at.runner.v1.Runner/GetFile',
            at_dot_runner_dot_v1_dot_runner__pb2.GetFileRequest.SerializeToString,
            at_dot_runner_dot_v1_dot_runner__pb2.FileChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/at.runner.v1.Runner/DeleteFile',
            at_dot_runner_dot_v1_dot_runner__pb2.DeleteFileRequest.SerializeToString,
            at_dot_runner_dot_v1_dot_runner__pb2.DeleteFileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListFiles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/at.runner.v1.Runner/ListFiles',
            at_dot_runner_dot_v1_dot_runner__pb2.ListFilesRequest.SerializeToString,
            at_dot_runner_dot_v1_dot_runner__pb2.ListFilesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Run(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/at.runner.v1.Runner/Run',
            at_dot_runner_dot_v1_dot_runner__pb2.RunRequest.SerializeToString,
            at_dot_runner_dot_v1_dot_runner__pb2.RunOutput.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RunPipeline(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/at.runner.v1.Runner/RunPipeline',
            at_dot_runner_dot_v1_dot_runner__pb2.RunPipelineRequest.SerializeToString,
            at_dot_runner_dot_v1_dot_runner__pb2.PipelineOutput.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
